version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=trades
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/trades_management
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=trades
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - selenium
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - 4444:4444
    environment:
      SE_OPTS: "--host selenium"